version: "3.1"
services:
  client:
    image: dep-of-env-kmla:frontend-v1.0.0
    build:
      context: ..
      dockerfile: depofenvkmla_client/Dockerfile
    restart: always
    ports:
      - "80:80"
    environment:
      GENERATE_SOURCEMAP: false